name: External Trigger Workflow

on:
  repository_dispatch:
    types:
      - deploy-request

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Event Information
        run: |
          echo "Repository Dispatch Triggered!"
          echo "Event Type: ${{ github.event.action }}"
          echo "Environment: ${{ github.event.client_payload.environment }}"