name: Multiple depending jobs running workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "This is building phase"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "This is testing phase"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "This is deployment phase"