name: Re Usable Build Workflow

on:
  workflow_call:
    inputs:
      app_name:
          description: Name of the application
          required: true
          type: string

      environment:
        description: Deployment environment
        required: true
        default: staging
        type: string

    secrets:
      docker_token:
        description: Docker Hub Token
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print build information
        run: |
          echo "Building : ${{ inputs.app_name }}"
          echo "Environment : ${{ inputs.environment }}"

      - name: Verify Docker Token Authentication
        run: |
          if [ -n "${{ secrets.docker_token }}" ]; then
            echo "The secret docker token set : true"
          else
            echo "The secret docker token set : false"
          fi
      