name: secret repository printing try

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: check if the secret exists.
        if: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "The secret set is : true"

      - name: Secret Masking Demo while trying to print a secret
        run: |
          echo "${{ secrets.MY_SECRET_MESSAGE }}"