name: Secret Repository Printing Demo

on:
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest

    env:
      MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE }}

    steps:
      - name: Check if secret exists
        run: |
          if [ -n "$MY_SECRET" ]; then
            echo "Secret exists: true"
          else
            echo "Secret exists: false"
          fi

      - name: Secret Masking Demo
        run: |
          echo "$MY_SECRET"